'\" t
.\"     Title: git-track
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 02/04/2010
.\"    Manual: \ \&
.\"    Source: \ \& 1.0
.\"  Language: English
.\"
.TH "GIT\-TRACK" "1" "02/04/2010" "\ \& 1\&.0" "\ \&"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-track \- set up a local branch to track a remote branch
.SH "SYNOPSIS"
.sp
\fBgit track\fR [\fB\-v\fR] [\fB\-n\fR] [\fB\-f\fR] [\fB\-b\fR \fI<remote_branch>\fR] [\fI<remote>\fR [\fI<local_branch>\fR]] \fBgit track\fR [\fB\-v\fR] [\fB\-n\fR] \fB\-d\fR \fI<local_branch>\fR
.SH "DESCRIPTION"
.sp
A simple shell script to ease the unnecessarily complex task of tracking a branch\&.
.SH "OPTIONS"
.PP
\fB\-v\fR
.RS 4
Print the git commands before executing them\&.
.RE
.PP
\fB\-n\fR
.RS 4
Don\(cqt run any of the git commands\&. Only print them, as in
\fB\-v\fR\&.
.RE
.PP
\fB\-f\fR
.RS 4
Don\(cqt do any checks on whether
\fI<local_branch>\fR
is tracking a branch already or that
\fI<remote_branch>\fR
exists\&.
.RE
.PP
\fB\-b\fR \fI<remote_branch>\fR
.RS 4
Don\(cqt reuse
\fI<local_branch>\fR
for the remote branch and use
\fI<remote_branch>\fR\&.
.RE
.PP
\fB\-d\fR
.RS 4
Stop
\fI<local_branch>\fR
from tracking anything\&.
.RE
.PP
<remote>
.RS 4
The remote where the branch you want to track exists\&.
.RE
.PP
<local_branch>
.RS 4
The local branch that will track the remote\&. If none given, use `git symbolic\-ref HEAD\e`\&.
.RE
.SH "EXIT STATUS"
.sp
0 on success and non\-zero on failure\&.
.SH "AUTHOR"
.sp
Gavin Beatty <gavinbeatty@gmail\&.com>
.SH "RESOURCES"
.sp
Website: http://code\&.google\&.com/p/git\-track/
.SH "REPORTING BUGS"
.sp
Please report all bugs and wishes to <gavinbeatty@gmail\&.com>
.SH "COPYING"
.sp
git\-track Copyright (C) 2010 Gavin Beatty, <gavinbeatty@gmail\&.com>
.sp
Free use of this software is granted under the terms of the GNU General Public License version 3, or at your option, any later version\&. (GPLv3+)
